### ISSUE TITLE
Reskin

### ISSUE THREAD

**Issue by ThatOnePers0n** [KindleModding/KWebBrew#2]
Hello, 
I like this project & reskinned it, can I put the reskinned version on a repo?

![koffee](https://user-images.githubusercontent.com/87896375/224219655-1f07ae97-542d-40d9-8b17-af8fa26e143b.png)

**Comment by ThatOnePers0n** [comment]
Also, I changed some of the app icons so they would load faster

**Comment by ThatHackerDudeFromCyberspace** [comment]
I might actually support theming in a later update, sure feel free to put it in a repo, but please reformat the credit section so it says `Bluebotlaboratories` instead of `BlueBotLaboratories`

Looks cool though, and yeah, I'll definitely update those icons in the future
The current bare-bones appearance is mainly due to the fact that this is mostly a proof-of-concept

The new default theme is probably going to take some... inspiration ;)

**Comment by ThatOnePers0n** [comment]
> I might actually support theming in a later update, sure feel free to put it in a repo, but please reformat the credit section so it says `Bluebotlaboratories` instead of `BlueBotLaboratories`
> 
> Looks cool though, and yeah, I'll definitely update those icons in the future The current bare-bones appearance is mainly due to the fact that this is mostly a proof-of-concept
> 
> The new default theme is probably going to take some... inspiration ;)

Thanks! Changed the credits (also just some inspiration...)

**Comment by ThatOnePers0n** [comment]
The GitHub account is here

https://github.com/KoffeeLauncher

**Comment by ThatHackerDudeFromCyberspace** [comment]
> The GitHub account is here
> 
> https://github.com/KoffeeLauncher

nice, I'll ping you here once theming support is added, should be easy to migrate KoffeeLauncher to it
